### ISSUE TITLE
Unicode is currently unsupported.

### ISSUE THREAD

**Issue by EliteTK** [dhobsd/castty#19]
Right now unicode does not appear to survive the recording and playback, it would be nice to have this working to allow for internationalization among other things.

**Comment by dhobsd** [comment]
This is largely due to setting `ISTRIP` in `rtt.c_iflag` in `castty.c:set_raw_input`. However, removing `ISTRIP` isn't enough: we need to validate that the UTF is valid and encode it in the JS output.

Unfortunately, JavaScript strings are UTF-16, so we can't just get away with supporting UTF-8 only.

**Comment by dhobsd** [comment]
UTF-8 inputs are supported as of d6d6c0d. I'm not super interested in supporting other input encodings.
