### ISSUE TITLE
Audio inputs with duplicated names

### ISSUE THREAD

**Issue by Cat-Ion** [dhobsd/castty#36]
When multiple audio devices have the same name, it is impossible to select anything but the first of them.

A proof of concept for a solution would be 
[this patch](https://github.com/dhobsd/castty/files/4908932/audio-by-index.txt), which will also allow you to specify an index with `-d` - although it would also make sense to have a separate option for that, to prevent confusion if a device has an integer as its name.

**Comment by dhobsd** [comment]
Sorry for the delay in reply!

I just pushed 7443dc271681f3ad, which I think may solve the problem. The device ID output in the enumeration is supposed to be distinct, but it's possible the device is accessible both directly and via some sound proxy like dmix or pulse. 

I'm closing this issue since this is the likely fix. If you're still experiencing this problem, please let me know! I'd especially appreciate the output of `castty record -l`.
